modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "imageframeclient/icon.png"
credits = "Originally by LOOHP, now maintained by Wakcedon"
authors = "${mod_authors}"

[[mixins]]
config = "imageframeclient.mixins.json"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,1.22)"
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    side = "BOTH"
